services:
  db:
    container_name: neosig_postgresql
    image: postgis/postgis:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USUARIO}
      - POSTGRES_PASSWORD=${DB_SENHA}
      - POSTGRES_DB=${DB_NOME}
    volumes:
      - ./src/data/init.sql:/docker-entrypoint-initdb.d/init.sql

  # backend-fastapi:
  #   container_name: neosig_backend_fastapi
  #   build:
  #     context: ./backend
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file: ".env"

  backend-php:
    container_name: neosig_backend_php
    build:
      context: ./backend-php
    ports:
      - 5000:80
    volumes:
      - ./backend-php:/var/www/html
    depends_on:
      - db
  # frontend:
  #   container_name: neosig_frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - 5173:5173
  #   env_file: ".env"
